### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by mattdeveluk** [naknode/football-db#1]
Installed football-db by following your guide, but when I want to register, use search or login, there is always 404 error on every single url other than homepage (index).

**Comment by naknode** [comment]
Thanks for first issue!

First of all, what commands did you type? What was the error message you received? What is your dev environment?

I need these answers to better properly assess the problem.

**Comment by mattdeveluk** [comment]
I did exactly what you say in guide, step by step, except running make.sh file, because I wasn't able to run trough databse setup, so edited config file manually. Using Xampp with PHP 7.1.4. Now getting 404 page when I try to navigate to other page than homepage, e.g when clicking on register, login button or trying to search. Also, there is this error on homepage:
`Warning: array_chunk(): Size parameter expected to be greater than 0 in C:\xampp7\htdocs\src\controllers\main.controller.php on line 9`

**Comment by naknode** [comment]
Good news @mattdeveluk. I noticed a few things wrong.

I have made the following changes:

- Take into account that no data can be introduced into the site. (thus no need for parsing data that doesn't exist)
- Make the 1st user created automatically an administrator
- Update tests accordingly

I also recommend switching to `npm` instead of `yarn` ever since `npm` released version 5. I also updated `make.sh` as well.

I hope this new update solves it for you, as I was able to do a dry-run successfully.

**Comment by mattdeveluk** [comment]
Update: Seems that it's not any error in code, just missing .htaccess file. I created one just to know, and now everything seems to work.

.htacces code:
`Options +FollowSymLinks
RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [L]`

**Comment by naknode** [comment]
Good deal. I should probably make a template asking for specifics so we waste less time on trivial things! Thanks for reporting in.
